"use client";

import NextLink from "next/link";
import { DiagramContainer } from "@/components/ui/diagram-container";
import { DocsHeader } from "@/components/ui/docs-header";
import { AlertBlock } from "@/components/ui/alert-block";
import { CodeBlock } from "@/components/ui/code-block";
import { JsonViewer } from "@/components/ui/json-viewer";
import { StepCard } from "@/components/ui/step-card";
import { Callout } from "@/components/ui/callout";
import { RequestHeaders } from "@/components/ui/request-headers";
import {
  Link,
  Clock,
  FileSearch,
  Shield,
  ArrowRight,
  CheckCircle2,
  XCircle,
  Lightbulb,
} from "lucide-react";
import {
  transactionFlowSequence,
  transactionIdFlowDiagram,
  consistencyDiagram,
  step1_initialRequest,
  step2_gatewayResponse,
  step3_providerWebhook,
  step4_providerCallback,
  step5_statusCheck,
  transactionIdBenefits,
  consistencyRules,
  flowSteps,
  errorScenarios,
  fhirRequestHeaders,
} from "./data";

const benefitIcons: Record<string, React.ReactNode> = {
  Link: <Link className="h-5 w-5" />,
  Clock: <Clock className="h-5 w-5" />,
  FileSearch: <FileSearch className="h-5 w-5" />,
  Shield: <Shield className="h-5 w-5" />,
};

export default function TransactionFlowPage() {
  return (
    <article className="relative">
      <DocsHeader
        badge="Transaction Flow"
        badgeColor="orange"
        title="Understanding the Transaction Flow"
        description="A detailed walkthrough of how requests move through the Gateway, and why the transaction_id is the critical link between all systems."
      />

      {/* Introduction */}
      <section id="intro" className="mb-16">
        <h2 className="mb-6 text-2xl font-bold text-slate-900">Introduction</h2>
        <p className="text-slate-600 leading-relaxed mb-6 text-lg">
          The WAH4PC Gateway uses an <strong>asynchronous request/response model</strong>. 
          When a healthcare provider requests patient data from another provider, the Gateway 
          orchestrates the entire flow without blocking. At the heart of this process is the{" "}
          <code className="rounded bg-slate-100 px-1.5 py-0.5 text-sm font-mono text-blue-700">
            transaction_id
          </code>
          —a unique identifier that links every step from initial request to final delivery.
        </p>
        
        <AlertBlock type="info" title="Why This Matters">
          Understanding the transaction flow is essential for both <strong>Requesters</strong> (those 
          asking for data) and <strong>Providers/Givers</strong> (those supplying data). Each party 
          must handle the <code className="text-sm">transaction_id</code> correctly for the system to work.
        </AlertBlock>

        <div className="mt-4 rounded-xl border border-cyan-200 bg-cyan-50/50 p-4 backdrop-blur-sm">
          <p className="text-sm text-cyan-900">
            <strong>Looking for the big picture?</strong> This page covers the <em>micro-level</em> details 
            of individual requests. For the <em>macro-level</em> provider lifecycle (registration, discovery, 
            monitoring), see the{" "}
            <NextLink href="/docs/system-flow" className="text-cyan-700 underline hover:text-cyan-900 font-medium">
              System Flow Overview
            </NextLink>
            .
          </p>
        </div>
      </section>

      {/* The Transaction ID Section */}
      <section id="transaction-id" className="mb-16">
        <h2 className="mb-6 text-2xl font-bold text-slate-900">
          The Transaction ID: Your Golden Thread
        </h2>
        
        <p className="text-slate-600 leading-relaxed mb-6">
          The <code className="rounded bg-slate-100 px-1.5 py-0.5 text-sm font-mono text-blue-700">
          transaction_id</code> is a UUID v4 prefixed with <code className="text-sm">txn_</code>. 
          It's generated by the Gateway the moment a request is received and follows the data 
          through every stage of processing.
        </p>

        <div className="mb-8 rounded-xl border border-slate-200 bg-white/50 backdrop-blur-sm p-6 text-center shadow-sm">
          <p className="text-sm font-mono text-slate-500 mb-2 uppercase tracking-wide">Example ID</p>
          <code className="text-xl sm:text-2xl font-mono text-blue-600 font-bold break-all">
            txn_a1b2c3d4-e5f6-7890-abcd-ef1234567890
          </code>
        </div>

        {/* Benefits Grid */}
        <h3 className="mb-6 text-lg font-semibold text-slate-900">Why It Matters</h3>
        <div className="grid gap-4 sm:grid-cols-2 mb-8">
          {transactionIdBenefits.map((benefit) => (
            <div
              key={benefit.title}
              className="group rounded-2xl border border-slate-200 bg-white/50 backdrop-blur-sm p-5 hover:shadow-md hover:border-blue-300 transition-all"
            >
              <div className="mb-3 flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 text-blue-600 group-hover:bg-blue-600 group-hover:text-white transition-colors">
                {benefitIcons[benefit.icon]}
              </div>
              <h4 className="mb-2 font-bold text-slate-900">{benefit.title}</h4>
              <p className="text-sm text-slate-600">{benefit.description}</p>
            </div>
          ))}
        </div>

        {/* Transaction ID Journey Diagram */}
        <h3 className="mb-6 text-lg font-semibold text-slate-900">The ID's Journey</h3>
        <DiagramContainer 
          chart={transactionIdFlowDiagram} 
          title="ID Propagation Flow"
          filename="id_journey.mmd"
          className="mb-6"
        />
      </section>

      {/* Visual Flow Section */}
      <section id="lifecycle" className="mb-16">
        <h2 className="mb-6 text-2xl font-bold text-slate-900">
          Complete Transaction Lifecycle
        </h2>
        <p className="text-slate-600 leading-relaxed mb-6">
          The diagram below shows the complete flow from when a Requester initiates a data 
          request to when they receive the final response. Notice how the{" "}
          <code className="text-sm">transaction_id</code> appears at every critical juncture.
        </p>
        
        <DiagramContainer 
          chart={transactionFlowSequence} 
          title="Sequence Diagram"
          filename="lifecycle_sequence.mmd"
          className="mb-8"
        />

        <AlertBlock type="warning" title="Key Observation">
          The Gateway <strong>never blocks</strong>. After returning the <code className="text-sm">transaction_id</code> to 
          the Requester (Step 6), it immediately proceeds to notify the Provider. The Requester 
          polls later using that same ID.
        </AlertBlock>
      </section>

      {/* Step by Step with JSON */}
      <section id="step-by-step" className="mb-16">
        <h2 className="mb-8 text-2xl font-bold text-slate-900">
          Step-by-Step with JSON Examples
        </h2>
        <p className="text-slate-600 leading-relaxed mb-8">
          Let's walk through each step with actual request/response payloads. Pay attention 
          to how the <code className="text-sm">transaction_id</code> propagates.
        </p>

        {/* Step 1: Initial Request */}
        <StepCard
          stepNumber={1}
          title="Requester Sends Initial Request"
          endpoint="POST /api/v1/fhir/request/{resourceType}"
          actor="Requester → Gateway"
          description="A healthcare app requests patient medication data from another provider. At this point, no transaction_id exists yet."
        >
          <RequestHeaders headers={fhirRequestHeaders} />
          <JsonViewer
            data={step1_initialRequest}
            title="Request Body"
          />
          <Callout type="note">
            The <code className="text-sm font-mono">targetId</code> identifies WHO has the data.
            The patient lookup fields (for example <code className="text-sm font-mono">patientIdentifiers</code>) specify WHICH patient.
          </Callout>
        </StepCard>

        {/* Step 2: Gateway Response */}
        <StepCard
          stepNumber={2}
          title="Gateway Returns transaction_id"
          endpoint="Response: 202 Accepted"
          actor="Gateway → Requester"
          description="The Gateway immediately responds with a transaction_id. This is the Requester's 'receipt' to track the request."
        >
          <JsonViewer
            data={step2_gatewayResponse}
            title="Response Body"
          />
          <Callout type="important">
            <strong>202 Accepted</strong> means "I've received your request and will process it." 
            It does NOT mean "here's your data." The Requester must poll the <code className="text-sm font-mono">status_url</code> later.
          </Callout>
        </StepCard>

        {/* Step 3: Provider Webhook */}
        <StepCard
          stepNumber={3}
          title="Gateway Notifies Provider (Giver)"
          endpoint="POST {provider.baseUrl}/fhir/process-query"
          actor="Gateway → Provider"
          description="The Gateway forwards the request to the Provider who has the patient data. The transaction_id is included."
        >
          <JsonViewer
            data={step3_providerWebhook}
            title="Webhook Payload to Provider"
          />
          <Callout type="critical">
            <strong>Provider: You MUST save this transaction_id!</strong> When you send data back, 
            you'll need to include it. Without it, the Gateway cannot match your response to the original request.
          </Callout>
        </StepCard>

        {/* Step 4: Provider Callback */}
        <StepCard
          stepNumber={4}
          title="Provider Sends Data via Callback"
          endpoint="POST /api/v1/fhir/receive/{resourceType}"
          actor="Provider → Gateway"
          description="After fetching the requested FHIR data, the Provider POSTs back to the Gateway. The same transaction_id MUST be included."
        >
          <RequestHeaders headers={fhirRequestHeaders} />
          <JsonViewer
            data={step4_providerCallback}
            title="Callback Payload from Provider"
          />
          <Callout type="important">
            The <code className="text-sm font-mono">transaction_id</code> in this payload is how the Gateway knows 
            which request this data fulfills. It's the correlation key.
          </Callout>
        </StepCard>

        {/* Step 5: Status Check */}
        <StepCard
          stepNumber={5}
          title="Requester Tracks Transaction Status"
          endpoint="GET /api/v1/transactions/{id}"
          actor="Requester → Gateway"
          description="The Requester polls transaction status using the transaction_id from Step 2. FHIR payload delivery is done through `/fhir/receive-results` webhook."
        >
          <CodeBlock
            code={step5_statusCheck}
            title="Status Check"
            language="HTTP"
          />
          <Callout type="success">
            Full circle! The same <code className="text-sm font-mono">transaction_id</code> from Step 2 
            is used to track completion and audit metadata. The journey is complete.
          </Callout>
        </StepCard>
      </section>


      {/* Consistency Rules */}
      <section id="consistency" className="mb-16">
        <h2 className="mb-6 text-2xl font-bold text-slate-900">
          Consistency Rules: The Non-Negotiables
        </h2>
        <p className="text-slate-600 leading-relaxed mb-6">
          For the system to work reliably, everyone must follow these rules:
        </p>

        <DiagramContainer 
          chart={consistencyDiagram} 
          title="Data Consistency Model"
          filename="consistency.mmd"
          className="mb-8"
        />

        <div className="grid gap-4 sm:grid-cols-2">
          {consistencyRules.map((item) => (
            <div
              key={item.rule}
              className="flex items-start gap-4 rounded-xl border border-slate-200 bg-white/50 backdrop-blur-sm p-5 hover:shadow-md transition-shadow"
            >
              <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-green-100 text-green-600">
                <CheckCircle2 className="h-5 w-5" />
              </div>
              <div>
                <h4 className="font-bold text-slate-900 mb-1">{item.rule}</h4>
                <p className="text-sm text-slate-600 leading-relaxed">{item.description}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Error Scenarios */}
      <section id="errors" className="mb-16">
        <h2 className="mb-6 text-2xl font-bold text-slate-900">
          Common Error Scenarios
        </h2>
        <p className="text-slate-600 leading-relaxed mb-6">
          Understanding what can go wrong helps you implement correctly. Here are common errors 
          related to <code className="text-sm font-mono">transaction_id</code> handling:
        </p>

        <div className="space-y-6">
          {errorScenarios.map((scenario) => (
            <div
              key={scenario.scenario}
              className="rounded-2xl border border-red-200 bg-red-50/30 p-4 sm:p-6 overflow-hidden"
            >
              <div className="mb-4 flex items-center gap-2">
                <XCircle className="h-5 w-5 shrink-0 text-red-500" />
                <h4 className="font-bold text-slate-900">{scenario.scenario}</h4>
              </div>
              <div className="grid gap-4 lg:grid-cols-2 mb-4">
                <div className="min-w-0">
                  <p className="mb-2 text-xs font-bold text-slate-500 uppercase tracking-wide">Request</p>
                  <CodeBlock
                    code={scenario.request}
                    showCopyButton={false}
                  />
                </div>
                <div className="min-w-0">
                  <p className="mb-2 text-xs font-bold text-slate-500 uppercase tracking-wide">Response</p>
                  <CodeBlock
                    code={scenario.response}
                    showCopyButton={false}
                  />
                </div>
              </div>
              <p className="text-sm text-slate-700">{scenario.explanation}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Detailed Steps Reference */}
      <section id="steps" className="mb-16">
        <h2 className="mb-6 text-2xl font-bold text-slate-900">
          Detailed Step Reference
        </h2>
        <p className="text-slate-600 leading-relaxed mb-6">
          A comprehensive breakdown of each step in the transaction lifecycle:
        </p>

        <div className="space-y-4">
          {flowSteps.map((step) => (
            <div
              key={step.step}
              className="group rounded-2xl border border-slate-200 bg-white/50 backdrop-blur-sm p-6 hover:shadow-md transition-shadow"
            >
              <div className="flex items-start gap-5">
                <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-blue-600 text-sm font-bold text-white shadow-md shadow-blue-200">
                  {step.step}
                </div>
                <div className="flex-1">
                  <div className="mb-2 flex flex-wrap items-center gap-2">
                    <h4 className="font-bold text-slate-900">{step.title}</h4>
                    <span className="rounded bg-slate-100 px-2 py-0.5 text-xs font-mono text-slate-600 font-medium">
                      {step.actor}
                    </span>
                  </div>
                  {step.endpoint !== "N/A" && step.endpoint !== "Internal" && (
                    <p className="mb-3 font-mono text-sm text-blue-600 bg-blue-50/50 inline-block px-2 py-1 rounded">{step.endpoint}</p>
                  )}
                  <p className="mb-4 text-sm text-slate-600 leading-relaxed">{step.description}</p>
                  <div className="flex items-start gap-2.5 rounded-xl bg-amber-50 p-3 border border-amber-100">
                    <Lightbulb className="mt-0.5 h-4 w-4 shrink-0 text-amber-600" />
                    <p className="text-sm text-amber-900">{step.keyPoint}</p>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Summary */}
      <section id="summary">
        <div className="rounded-2xl border border-blue-200 bg-blue-50/50 p-8 backdrop-blur-sm">
          <h2 className="mb-4 text-xl font-bold text-slate-900">Summary</h2>
          <ul className="space-y-3 text-slate-700">
            {[
              "The transaction_id is generated by the Gateway and returned immediately.",
              "Both Requesters and Providers must use this ID in all related operations.",
              "Providers MUST include the ID in callbacks—without it, the data cannot be matched.",
              "The ID enables async processing, audit trails, and idempotency.",
              "Treat the transaction_id as immutable—never modify, always preserve."
            ].map((text, i) => (
              <li key={i} className="flex items-start gap-3">
                <ArrowRight className="mt-1 h-4 w-4 shrink-0 text-blue-600" />
                <span>{text}</span>
              </li>
            ))}
          </ul>
        </div>
      </section>
    </article>
  );
}
